api/urls.py
from django.urls import include, path
from rest_framework.documentation import include_docs_urls
from rest_framework.routers import SimpleRouter
from rest_framework_swagger.views import get_swagger_view
from api.views import WineViewSet

API_TITLE = 'winesearch API'
API_DESC = 'A web API for creating, modifying and deleting Wines.'

docs_view = include_docs_urls (
    title=API_TITLE,
    description=API_DESC
)

# Swagger view
schema_view = get_swagger_view (title=API_TITLE)

# Default view
'''
schema_view = get_schema_view(
	title=API_TITLE,
	renderer_classes=[OpenAPIRenderer]
)
'''

router = SimpleRouter ()
router.register (r'wines', WineViewSet, base_name='wines')
# urlpatterns = router.urls

# The API URLs are now determined automatically by the router.
urlpatterns = [
    path ( '', include ( router.urls ) ),
    path ( 'docs/', docs_view ),
    path ( 'swagger-docs/', schema_view )
    # path('schema/', schema_view)
]

'''
urlpatterns = [
	path('schema/', schema_view),
	path('wines/', views.WineListAPIView.as_view(), name='wine_api'),
	path('wines/<int:pk>/', views.WineDetailAPIView.as_view(), name='wine_detail_api'),
]
'''

mysite/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.urls import path, include



urlpatterns = [
    #path('/', )
    path('', include('winesearch.urls')),
    #path('winesearch/', include('winesearch.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('social_django.urls', namespace='social')),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},
         name='logout'),

    path('winesearch/api/rest-auth/', include('rest_auth.urls')),
    path('winesearch/api/rest-auth/registration/', include('rest_auth.registration.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('winesearch/api/', include('api.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

winesearch/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('wines/', views.WineListView.as_view(), name='wine_list'),
    path('wines/<int:pk>/', views.WineDetailView.as_view(), name='wine_detail'),
    path('wines/<int:pk>/delete/', views.WineDeleteView.as_view(), name='wine_delete'),
    path('wines/<int:pk>/update/', views.WineUpdateView.as_view(), name='wine_update'),
    path('wines/new/', views.WineCreateView.as_view(), name='wine_new'),
    path('winery/', views.WineryListView.as_view(), name='winery_list'),
    path('winery/<int:pk>/', views.WineryDetailView.as_view(), name='winery'),
    path('wine_filter/', views.WineFilterView.as_view(), name='wine_filter'),
    path('winery_filter/', views.WineryFilterView.as_view(), name='winery_filter'),
]

# ReverseMatch -->@method_decorator(login_required, name='dispatch')   refer to name='xxx'

winesearch/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.

# Reference: https://docs.djangoproject.com/en/2.1/ref/models/options/#unique-together
from django.db import models
from django.urls import reverse


class Country(models.Model):
    country_id = models.AutoField(primary_key=True)
    country_name = models.CharField(max_length=45, unique=True) #outhgt to be unique

    class Meta:
        db_table = 'country'

    def __str__(self):
        return '{}'.format(self.country_name)


class Province(models.Model):
    province_id = models.AutoField(primary_key=True)
    province_name = models.CharField(max_length=45)
    country = models.ForeignKey(Country, on_delete=models.DO_NOTHING)

    class Meta:
        unique_together = [['country', 'province_name']]
        db_table = 'province'


    def __str__(self):
        return '{}, {}'.format(self.province_name, self.country.country_name)


class Region1(models.Model):
    region1_id = models.AutoField(primary_key=True)
    region1_name = models.CharField(max_length=100)
    province = models.ForeignKey(Province, on_delete=models.DO_NOTHING)

    class Meta:
        unique_together = [['province', 'region1_name']]
        db_table = 'region1'

    def __str__(self):
        return '{}, {}'.format(self.region1_name, self.province.province_name)


class Region2(models.Model):
    region2_id = models.AutoField(primary_key=True)
    region2_name = models.CharField(max_length=100)
    region1 = models.ForeignKey(Region1, on_delete=models.DO_NOTHING)

    class Meta:
        unique_together = [['region1', 'region2_name']]
        db_table = 'region2'

    def __str__(self):
        return '{}'.format(self.region2_name)


class Variety(models.Model):
    variety_id = models.AutoField(primary_key=True)
    variety_name = models.CharField(max_length=45, unique=True)

    region1 = models.ManyToManyField(Region1, through='VarietyRegion1')
    region2 = models.ManyToManyField(Region2, through='VarietyRegion2')

    class Meta:
        db_table = 'variety'

    def __str__(self):
        return '{}'.format(self.variety_name)


class VarietyRegion1(models.Model):     #Joint model between Region1 and Variety
    region1 = models.ForeignKey(Region1, on_delete=models.DO_NOTHING)
    variety = models.ForeignKey(Variety, on_delete=models.DO_NOTHING)
    variety_region1_id = models.AutoField(primary_key=True)

    class Meta:
        db_table = 'variety_region1'

class VarietyRegion2(models.Model):     #Joint model between Region2 and Variety
    variety = models.ForeignKey(Variety, on_delete=models.DO_NOTHING)
    region2 = models.ForeignKey(Region2, on_delete=models.DO_NOTHING)
    variety_region2_id = models.AutoField(primary_key=True)

    class Meta:
        db_table = 'variety_region2'


class Taster(models.Model):
    taster_id = models.AutoField(primary_key=True)
    taster_name = models.CharField(max_length=45)
    twitter_handles = models.CharField(max_length=45, blank=True, null=True)
    points = models.SmallIntegerField(blank=True, null=True, default=0)

    class Meta:
        db_table = 'taster'

    def __str__(self):
        return '{}'.format(self.taster_name)


class Wine(models.Model):
    wine_id = models.AutoField(primary_key=True)
    wine = models.CharField(max_length=150)
    description = models.CharField(max_length=1000, blank=True, null=True)
    designation = models.CharField(max_length=100, blank=True, null=True)
    price = models.FloatField(blank=True, null=True)
    winery = models.ForeignKey('Winery', models.DO_NOTHING)
    country = models.ForeignKey(Country, blank=True, null=True, on_delete=models.DO_NOTHING)
    province = models.ForeignKey(Province, blank=True, null=True, on_delete=models.DO_NOTHING)
    region1 = models.ForeignKey(Region1, blank=True, null=True, on_delete=models.DO_NOTHING)
    region2 = models.ForeignKey(Region2, blank=True, null=True, on_delete=models.DO_NOTHING)
    variety = models.ForeignKey(Variety, blank=True, null=True, on_delete=models.DO_NOTHING)

    taster = models.ManyToManyField(Taster, through='WineTaster', blank=True, related_name='wines')

    class Meta:
        managed = False
        db_table = 'wine'
        ordering = ['wine']
        verbose_name = 'Wine'
        verbose_name_plural = 'Wines'


    def __str__(self):
        return '{}, {}, {}, {}'.format(self.wine, self.description, self.designation, self.price)

    def get_absolute_url(self):
        # return reverse('wine_detail', args=[str(self.id)])
        return reverse('wine_detail', kwargs={'pk': self.pk})

    # For filters.py: wine(label), description, variety, region2, region1, province, country, winery, price, points:
    # @property
    # def winery_names(self):
    #     wineries = self.winery.select_related('wine__winery').order_by('wine__winery__winery_name')
    #
    #     winery_names = []
    #     for winery in wineries:
    #         winery_name = winery.winery_name
    #         if winery_name is None:
    #             continue
    #         if winery_name not in winery_names:
    #             winery_names.append(winery_name)
    #     return winery_names

    @property
    def province_names(self):
        """
        Returns a list of Province (names only) associated with a Wine.
        Not all Wine are associated with a Province. In such cases the
        Queryset will return as <QuerySet [None]> and the list will need to be checked for
        None or a TypeError (sequence item 0: expected str instance, NoneType found) runtime
        error will be thrown.
        :return: string
        """
        countries = self.province.select_related('country__province').order_by(
            'country__province__province_name')

        province_names = []

        for country in countries:
            if not country.province:
                continue
            province_name = country.province.province_name
            if province_name not in province_names:
                province_names.append(province_name)
        return ', '.join(province_names)


class WineTaster(models.Model):     #Joint model between Wine and Taster
    wine_taster_id = models.AutoField(primary_key=True)
    taster = models.ForeignKey(Taster, on_delete=models.DO_NOTHING, related_name='related_taster')
    wine = models.ForeignKey(Wine, on_delete=models.DO_NOTHING)

    class Meta:
        db_table = 'wine_taster'


class Winery(models.Model):
    winery_id = models.AutoField(primary_key=True)
    winery_name = models.CharField(max_length=100, blank=True, null=True)
    # Can't do select_related for many-to-many.
    # Intermediate model (Winery -> WineryVariety <- Variety)
    variety = models.ManyToManyField(Variety, through='WineryVariety')

    class Meta:
        db_table = 'winery'

    def __str__(self):
        return '{}'.format(self.winery_name)


class WineryVariety(models.Model):      #Joint model between Winery and Variety
    variety = models.ForeignKey(Variety, on_delete=models.DO_NOTHING)
    winery = models.ForeignKey(Winery, on_delete=models.DO_NOTHING)
    winery_variety_id = models.AutoField(primary_key=True)

    class Meta:
        db_table = 'winery_variety'

winesearch/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from winesearch.models import Wine
from winesearch.models import Winery

#  I want to create a WineForm, which is based on Wine model. By using .ModelForm,
# I can "borrow" components from the Wine model to avoid redundancy.

class WineForm(forms.ModelForm):
    class Meta:
        model = Wine
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'submit'))


class WineryForm(forms.ModelForm):
    class Meta:
        model = Winery
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.add_input(Submit('submit', 'submit'))

winesearch/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
import datetime
from django.views import generic
from django.urls import reverse_lazy

from .models import Country, Province, Region1, Region2, Variety, Wine, Winery, Taster
from .forms import WineForm
from .filters import WineFilter
from .filters import WineryFilter

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django_filters.views import FilterView
from django.utils import timezone


def index(request):
   return HttpResponse("Hello, world. You're at the Winesearch Sites index.")


#Take the template and displays: Non-dynamic content
class AboutPageView(generic.TemplateView):
    template_name = 'winesearch/about.html'


class HomePageView(generic.TemplateView):
    template_name = 'winesearch/home.html'


#The SiteListView() class requires an ORM query that retrieves all Winesearch records.
#all_entries = Entry.objects.all()
class WineListView(generic.ListView):
    model = Wine
    context_object_name = 'wines'
    template_name = 'winesearch/wine_list.html'
    paginate_by = 4000

    #def dispatch(self, *args, **kwargs):
        #return super().dispatch(*args, **kwargs)
    # .select_related can only work with Foreignkey

    def get_queryset(self):
        return Wine.objects.select_related('winery').order_by('wine')


#@method_decorator(login_required, name='dispatch')
class WineDetailView(generic.DetailView):
    model = Wine
    context_object_name = 'wine'
    template_name = 'winesearch/wine_detail.html'

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        return Wine.objects \
            .select_related('country', 'province', 'region1', 'region2', 'variety') \
            .order_by('wine')


@method_decorator(login_required, name='dispatch')
class WineryListView(generic.ListView):
    model = Winery
    context_object_name = 'wineries'
    template_name = 'winesearch/winery_list.html'
    paginate_by = 1000

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        return Winery.objects \
            .order_by('winery_name')


@method_decorator(login_required, name='dispatch')
class WineryDetailView(generic.DetailView):
    model = Winery
    context_object_name = 'winery'
    template_name = 'winesearch/winery_detail.html'


    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        return Winery.objects \
            .order_by('winery_name')


@method_decorator(login_required, name='dispatch')
class WineCreateView(generic.CreateView):
    model = Wine
    form_class = WineForm
    success_message = "Wine created successfully"
    template_name = 'winesearch/wine_new.html'
    # fields = '__all__' <-- superseded by form_class]
    #  success_url = reverse_lazy('wines/wine_list')

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def post(self, request):
        form = WineForm(request.POST)
        if form.is_valid():
            wine = form.save(commit=False)
            wine.save()
            return redirect(wine) # shortcut to object's get_absolute_url()

        return render(request, 'winesearch/wine_new.html', {'form': form})

    def get(self, request):
        form = WineForm()
        return render(request, 'winesearch/wine_new.html', {'form': form})


@method_decorator(login_required, name='dispatch')
class WineUpdateView(generic.UpdateView):
    model = Wine
    form_class = WineForm
    # fields = '__all__' <-- superseded by form_class
    context_object_name = 'wine'
    #pk_url_kwarg = 'wine_pk'
    success_message = "Wine updated successfully"
    template_name = 'winesearch/wine_update.html'

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        wine = form.save(commit=False)
        wine.updated_by = self.request.user
        wine.updated_at = timezone.now()
        wine.save()

        return HttpResponseRedirect(wine.get_absolute_url())
        # return render(self.request, 'winesearch/wine_update.html', {'form': form})


@method_decorator(login_required, name='dispatch')
class WineDeleteView(generic.DeleteView):
    model = Wine
    success_message = "Wine deleted successfully"
    success_url = reverse_lazy('wine_list')
    context_object_name = 'wine'
    template_name = 'winesearch/wine_delete.html'

    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)



class PaginatedFilterView(generic.View):
    def get_context_data(self, **kwargs):
        context = super(PaginatedFilterView, self).get_context_data(**kwargs)
        if self.request.GET:
            querystring = self.request.GET.copy()
            if self.request.GET.get('page'):
                del querystring['page']
            context['querystring'] = querystring.urlencode()
        return context


class WineFilterView(PaginatedFilterView, FilterView):
    model = Wine
    #form_class = SearchForm
    filterset_class = WineFilter
    context_object_name = 'wine_list'
    template_name = 'winesearch/wine_filter.html'
    paginate_by = 4000


class WineryFilterView(PaginatedFilterView, FilterView):
    model = Winery
    #form_class = SearchForm
    filterset_class = WineryFilter
    context_object_name = 'winery_list'
    template_name = 'winesearch/winery_filter.html'
    paginate_by = 4000

winesearch/templates/winesearch/about.html
{% extends 'winesearch/base.html' %}

{% block content %}

<h2><font color='#d2b786'>About Winesearch</font></h2>

<p> This site combines  Kaggle' Dataset  <a href="https://www.kaggle.com/zynicide/wine-reviews"
                                  alt="xxxxxxxxxx">Wine Reviews</a>
</p>(This site is a class project for SI664.)</p>



{% endblock content %}

winesearch/templates/winesearch/base.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="description" content="UMSI SI664 Django winesearch app">
    <meta name="keywords" content="SI664, Winesearch, Python, MySQL, Django, Bootstrap">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=yes">

    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
          crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/wine.css' %}">
    <link rel="stylesheet" href="{% static 'red-wine-in-kitchen_4460x4460.jpg' %}">

    <title>{% block title %}SI 664 Winesearch{% endblock title %}</title>

      <style>
        h1 {font-size: 40px;}
        h2 {font-size: 30px;}
        p {font-size: 14px;}
      </style>
  </head>


  <body>

    <nav class="navbar navbar-expand-sm navbar-dark navbar-custom sticky-top px-4 py-2">
    <div class="row">
      <a class="navbar-brand" href="{% url 'home' %}">SI664 Winesearch</a>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'about' %}">about</a>

      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'wine_filter' %}">wines</a>
       <li class="nav-item">
        {% if request.user.is_authenticated %}

        <a class="nav-link" href="{% url 'logout' %}">logout</a>
        {% else %}
        <a class="nav-link" href="{% url 'login' %}">login</a>

        {% endif %}

       </li>
     </ul>
    </div>
    </nav>

    <main class="px-4 py-3">
      <div class="container-fluid">

        <!--{{request.user}}-->
        {% block content %}
        {% endblock %}

    <!-- You will not be able to see this. -->

      </div>
    </main>

    <footer class="px-4 py-2">
        <img src="/static/large-wooden-wine-barells-in-frame_4460x4460.jpg" class="center" width="300" height="300">
        <img src="/static/red-wine-in-kitchen_4460x4460.jpg" class="center" width="300" height="300">
        <img src="/static/sparkling-white-wine-and-grapes_4460x4460.jpg" class="center" width="300" height="300">
        <img src="/static/wine-barrels-in-wooden-structure_4460x4460.jpg" class="center" width="300" height="300">
        <p>Copyright &copy; 2018 <a href="mailto:lopezy@umich.edu">Yuko Lopez</a></p>

    </footer>

    <!-- Get <script> tags: https://getbootstrap.com/docs/4.0/getting-started/download/ -->
    <!-- Order: jquery, popper, bootstrap -->

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous">
    </script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" \
            crossorigin="anonymous">
    </script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous">
    </script>
  </body>
</html>


<ul class="navbar-nav mr-auto">
  <!-- existing list items -->
</ul>

winesearch/templates/winesearch/home.html
{% extends 'winesearch/base.html' %}

{% block content %}
   <h2><b><font color='#d2b786'>Wine Search</font></b></h2>

    <p>(This site is a class project for SI664.)</p>
{% endblock content %}

winesearch/templates/winesearch/pagination.html
<!-- https://www.w3schools.com/bootstrap4/bootstrap_pagination.asp -->
<nav>
  {% if is_paginated %}
  <ul class="pagination pagination-sm justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link"
           href="?page={{ page_obj.previous_page_number }}{% if querystring %}&amp;{{ querystring }}{% endif %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled"><span>&laquo;</span></li>
    {% endif %}

    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="page-item active">
            <span class="page-link">{{ i }}
              <span class="sr-only">Current</span>
            </span>
        </li>
      {% else %}
        <li class="page-item">
          <a class="page-link"
          href="?page={{ i }}{% if querystring %}&amp;{{ querystring }}{% endif %}" aria-label="Current">{{ i }}</a>
        </li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link"
           href="?page={{ page_obj.next_page_number }}{% if querystring %}&amp;{{ querystring }}{% endif %}"
           aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    {% else %}
      <li class="page-item disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
  {% endif %}
</nav>

winesearch/templates/winesearch/wine_detail.html
{% extends 'winesearch/base.html' %}


   <!-- safe filter on for raw HTML stored in wine database -->
{% block content %}
    {% spaceless %}

    {% if wine.country.all %}
      {% for country in wine.country.all %}
        {% if country.province.region1.region2.variety %}
          {% ifchanged country.province.region1.region2.variety.variety_id %}
            {% if forloop.first %}
                {{ country.province.region1.region2.variety.variety_name.strip }}
            {% else %}
                {{ country.province.region1.region2.variety.variety_name.strip }}
            {% endif %}
          {% endifchanged %}
        {% elif country.province.region1.region2 %}
            {% ifchanged country.province.region1.region2.region2_id %}
                {% if forloop.first %}
                     {{ country.province.region1.region2.region2_name.strip }}
                {% else %}
                    {{ country.province.region1.region2.region2_name }}
                {% endif %}
            {% endifchanged %}
        {% elif country.province.region1 %}
            {% ifchanged country.province.region1.region_id %}
                {% if forloop.first %}
                    {{ country.region1.region1_name.strip }}
                {% else %}
                    {{ country.region1.region1_name.strip }}
                {% endif %}
            {% endifchanged %}
        {% elif country.province %}
            {% ifchanged country.province.province_id %}
                {% if forloop.first %}
                    {{ country.province.province_name.strip }}
                {% else %}
                    {{ country.province.province_name.strip }}
                {% endif %}
            {% endifchanged %}

        {% endif %}
      {% endfor %}
    {% endif %}
    {% endspaceless %}

    {% spaceless %}
           <p>
             {% for country in wine.country.all %}
               {% if forloop.last %}    <!-- True if this is the last time through the loop -->
                 {{ country.country_name.strip }}
               {% else %}
                 {{ country_area.country_area_name.strip }}
               {% endif %}
             {% endfor %}
           </p>
    {% endspaceless %}

<!--Add new rows for: province, region1, reion2, variety, and country names -->
     {% if wine.wine %}
       <div class="row">
         <div class="col-sm-2">
             <p><b>Label: </b></p>
         </div>
       <div class="col-sm-10">
           <p>{{ wine.wine }}</p>
       </div>
      </div>
    {% endif %}

    {% if wine.winery %}
       <div class="row">
         <div class="col-sm-2">
           <p><b>Winery: </b></p>
         </div>
       <div class="col-sm-10">
           <p>{{ wine.winery }}</p>
       </div>
      </div>
    {% endif %}

    {% if wine.variety %}
       <div class="row">
         <div class="col-sm-2">
           <p><b>Variety: </b></p>
         </div>
       <div class="col-sm-10">
           <p>{{ wine.variety.variety_name }}</p>
       </div>
      </div>
     {% endif %}

    {% if wine.description %}
       <div class="row">
         <div class="col-sm-2">
           <p><b>Description: </b></p>
         </div>
       <div class="col-sm-10">
           <p>{{ wine.description }}</p>
       </div>
      </div>
    {% endif %}

    {% if wine.designation %}
       <div class="row">
         <div class="col-sm-2">
           <p><b>Designation: </b></p>
         </div>
       <div class="col-sm-10">
           <p>{{ wine.designation }}</p>
       </div>
      </div>
    {% endif %}

    {% if wine.provinces %}
        <div class="row">
         <div class="col-sm-2">
           <p><b>Province: </b></p>
         </div>
       <div class="col-sm-10">
           <p>{{ wine.province.province_names }}</p>
       </div>
      </div>
    {% endif %}


     {% if wine.region1 %}
       <div class="row">
         <div class="col-sm-2">
           <p><b>Region: </b></p>
         </div>
       <div class="col-sm-10">
           <p>{{ wine.region1.region1_name }}</p>
       </div>
      </div>
     {% endif %}

    {% if wine.region2 %}
       <div class="row">
         <div class="col-sm-2">
             <p><b>Sub Region: </b></p>
         </div>
       <div class="col-sm-10">
           <p>{{ wine.region2.region2_name }}</p>
       </div>
      </div>
     {% endif %}

    {% if wine.country %}
       <div class="row">
         <div class="col-sm-2">
           <p><b>Country: </b></p>
         </div>
       <div class="col-sm-10">
           <p>{{ wine.country }}</p>
       </div>
      </div>
    {% endif %}

    {% if wine.price %}
       <div class="row">
         <div class="col-sm-2">
           <p><b>Price ($ US): </b></p>
         </div>
       <div class="col-sm-10">
           <p>{{ wine.price }}</p>
       </div>
      </div>
    {% endif %}

    {% for wt in wine.winetaster_set.all %}
       <div class="row">
         <div class="col-sm-2">
           <p><b>Points: </b></p>
         </div>
       <div class="col-sm-10">
           <p>{{ wt.taster.points }}</p>
       </div>
      </div>
    {% endfor %}

    {% for tn in wine.winetaster_set.all %}
       <div class="row">
         <div class="col-sm-2">
           <p><b>Taster Name: </b></p>
         </div>
       <div class="col-sm-10">
           <p>{{ tn.taster.taster_name }}</p>
       </div>
      </div>
    {% endfor %}

    {% if request.user.is_authenticated %}
    <button> <a class="btn btn-outline-danger" href="{% url "wine_delete" wine.wine_id %}">Delete</a></button>
    <button> <a class="btn btn-outline-danger" href="{% url "wine_update" wine.wine_id %}">Update</a></button>
    {% endif %}

 {% endblock content %}